on:
  push:
    branches: [main]
  pull_request:
name: Flatpak
jobs:
  flatpak:
    name: Build flatpak from main
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-41
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: DWXMLCreator.flatpak
        manifest-path: com.github.alexkdeveloper.dwxmlcreator.json
        cache-key: flatpak-builder-${{ github.sha }}
