on:
  push:
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-41
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: DWXMLCreator.flatpak
        manifest-path: com.github.alexkdeveloper.dwxmlcreator.json
        cache-key: flatpak-builder-${{ github.sha }}
